<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WaterQuality.Common\WaterQuality.Common.csproj" />
    <ProjectReference Include="..\WaterQuality.Repository\WaterQuality.Repository.csproj" />
  </ItemGroup>

</Project>
